// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: lifeguard.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the lifeguard details for creation.
type CreateLifeguardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name              string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Login             string `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	PasswordHash      string `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	YearsOfExperience int32  `protobuf:"varint,4,opt,name=years_of_experience,json=yearsOfExperience,proto3" json:"years_of_experience,omitempty"`
	Specialization    string `protobuf:"bytes,5,opt,name=specialization,proto3" json:"specialization,omitempty"`
	OnMission         bool   `protobuf:"varint,6,opt,name=on_mission,json=onMission,proto3" json:"on_mission,omitempty"`
}

func (x *CreateLifeguardRequest) Reset() {
	*x = CreateLifeguardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lifeguard_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLifeguardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLifeguardRequest) ProtoMessage() {}

func (x *CreateLifeguardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lifeguard_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLifeguardRequest.ProtoReflect.Descriptor instead.
func (*CreateLifeguardRequest) Descriptor() ([]byte, []int) {
	return file_lifeguard_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLifeguardRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateLifeguardRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *CreateLifeguardRequest) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *CreateLifeguardRequest) GetYearsOfExperience() int32 {
	if x != nil {
		return x.YearsOfExperience
	}
	return 0
}

func (x *CreateLifeguardRequest) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

func (x *CreateLifeguardRequest) GetOnMission() bool {
	if x != nil {
		return x.OnMission
	}
	return false
}

// The response message containing the ID of the newly created lifeguard.
type CreateLifeguardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateLifeguardResponse) Reset() {
	*x = CreateLifeguardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lifeguard_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLifeguardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLifeguardResponse) ProtoMessage() {}

func (x *CreateLifeguardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lifeguard_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLifeguardResponse.ProtoReflect.Descriptor instead.
func (*CreateLifeguardResponse) Descriptor() ([]byte, []int) {
	return file_lifeguard_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLifeguardResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// The request message containing the ID of the lifeguard to retrieve.
type GetLifeguardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetLifeguardRequest) Reset() {
	*x = GetLifeguardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lifeguard_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLifeguardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLifeguardRequest) ProtoMessage() {}

func (x *GetLifeguardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lifeguard_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLifeguardRequest.ProtoReflect.Descriptor instead.
func (*GetLifeguardRequest) Descriptor() ([]byte, []int) {
	return file_lifeguard_proto_rawDescGZIP(), []int{2}
}

func (x *GetLifeguardRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// The response message containing the lifeguard details.
type GetLifeguardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Login             string `protobuf:"bytes,3,opt,name=login,proto3" json:"login,omitempty"`
	PasswordHash      string `protobuf:"bytes,4,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	YearsOfExperience int32  `protobuf:"varint,5,opt,name=years_of_experience,json=yearsOfExperience,proto3" json:"years_of_experience,omitempty"`
	Specialization    string `protobuf:"bytes,6,opt,name=specialization,proto3" json:"specialization,omitempty"`
	OnMission         bool   `protobuf:"varint,7,opt,name=on_mission,json=onMission,proto3" json:"on_mission,omitempty"`
	CreatedAt         string `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // You can use string or google.protobuf.Timestamp
}

func (x *GetLifeguardResponse) Reset() {
	*x = GetLifeguardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lifeguard_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLifeguardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLifeguardResponse) ProtoMessage() {}

func (x *GetLifeguardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lifeguard_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLifeguardResponse.ProtoReflect.Descriptor instead.
func (*GetLifeguardResponse) Descriptor() ([]byte, []int) {
	return file_lifeguard_proto_rawDescGZIP(), []int{3}
}

func (x *GetLifeguardResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetLifeguardResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetLifeguardResponse) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *GetLifeguardResponse) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *GetLifeguardResponse) GetYearsOfExperience() int32 {
	if x != nil {
		return x.YearsOfExperience
	}
	return 0
}

func (x *GetLifeguardResponse) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

func (x *GetLifeguardResponse) GetOnMission() bool {
	if x != nil {
		return x.OnMission
	}
	return false
}

func (x *GetLifeguardResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// The request message containing the lifeguard details for updating.
type UpdateLifeguardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Login             string `protobuf:"bytes,3,opt,name=login,proto3" json:"login,omitempty"`
	PasswordHash      string `protobuf:"bytes,4,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	YearsOfExperience int32  `protobuf:"varint,5,opt,name=years_of_experience,json=yearsOfExperience,proto3" json:"years_of_experience,omitempty"`
	Specialization    string `protobuf:"bytes,6,opt,name=specialization,proto3" json:"specialization,omitempty"`
	OnMission         bool   `protobuf:"varint,7,opt,name=on_mission,json=onMission,proto3" json:"on_mission,omitempty"`
}

func (x *UpdateLifeguardRequest) Reset() {
	*x = UpdateLifeguardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lifeguard_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLifeguardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLifeguardRequest) ProtoMessage() {}

func (x *UpdateLifeguardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lifeguard_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLifeguardRequest.ProtoReflect.Descriptor instead.
func (*UpdateLifeguardRequest) Descriptor() ([]byte, []int) {
	return file_lifeguard_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateLifeguardRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateLifeguardRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateLifeguardRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UpdateLifeguardRequest) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *UpdateLifeguardRequest) GetYearsOfExperience() int32 {
	if x != nil {
		return x.YearsOfExperience
	}
	return 0
}

func (x *UpdateLifeguardRequest) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

func (x *UpdateLifeguardRequest) GetOnMission() bool {
	if x != nil {
		return x.OnMission
	}
	return false
}

// The response message confirming the lifeguard update.
type UpdateLifeguardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UpdateLifeguardResponse) Reset() {
	*x = UpdateLifeguardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lifeguard_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLifeguardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLifeguardResponse) ProtoMessage() {}

func (x *UpdateLifeguardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lifeguard_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLifeguardResponse.ProtoReflect.Descriptor instead.
func (*UpdateLifeguardResponse) Descriptor() ([]byte, []int) {
	return file_lifeguard_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateLifeguardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// The request message containing the ID of the lifeguard to delete.
type DeleteLifeguardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteLifeguardRequest) Reset() {
	*x = DeleteLifeguardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lifeguard_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLifeguardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLifeguardRequest) ProtoMessage() {}

func (x *DeleteLifeguardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lifeguard_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLifeguardRequest.ProtoReflect.Descriptor instead.
func (*DeleteLifeguardRequest) Descriptor() ([]byte, []int) {
	return file_lifeguard_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteLifeguardRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// The response message confirming the lifeguard deletion.
type DeleteLifeguardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteLifeguardResponse) Reset() {
	*x = DeleteLifeguardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lifeguard_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLifeguardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLifeguardResponse) ProtoMessage() {}

func (x *DeleteLifeguardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lifeguard_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLifeguardResponse.ProtoReflect.Descriptor instead.
func (*DeleteLifeguardResponse) Descriptor() ([]byte, []int) {
	return file_lifeguard_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteLifeguardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_lifeguard_proto protoreflect.FileDescriptor

var file_lifeguard_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6c, 0x69, 0x66, 0x65, 0x67, 0x75, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0xde, 0x01, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4c, 0x69, 0x66, 0x65, 0x67, 0x75, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x23, 0x0a, 0x0d,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x48, 0x61, 0x73,
	0x68, 0x12, 0x2e, 0x0a, 0x13, 0x79, 0x65, 0x61, 0x72, 0x73, 0x5f, 0x6f, 0x66, 0x5f, 0x65, 0x78,
	0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11,
	0x79, 0x65, 0x61, 0x72, 0x73, 0x4f, 0x66, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63,
	0x65, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x70, 0x65, 0x63, 0x69,
	0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x6e, 0x5f,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x6f,
	0x6e, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x29, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4c, 0x69, 0x66, 0x65, 0x67, 0x75, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x25, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x66, 0x65, 0x67, 0x75,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x8b, 0x02, 0x0a, 0x14, 0x47,
	0x65, 0x74, 0x4c, 0x69, 0x66, 0x65, 0x67, 0x75, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x23, 0x0a,
	0x0d, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x48, 0x61,
	0x73, 0x68, 0x12, 0x2e, 0x0a, 0x13, 0x79, 0x65, 0x61, 0x72, 0x73, 0x5f, 0x6f, 0x66, 0x5f, 0x65,
	0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x11, 0x79, 0x65, 0x61, 0x72, 0x73, 0x4f, 0x66, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e,
	0x63, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x70, 0x65, 0x63,
	0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x6e,
	0x5f, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x6f, 0x6e, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xee, 0x01, 0x0a, 0x16, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4c, 0x69, 0x66, 0x65, 0x67, 0x75, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x23, 0x0a,
	0x0d, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x48, 0x61,
	0x73, 0x68, 0x12, 0x2e, 0x0a, 0x13, 0x79, 0x65, 0x61, 0x72, 0x73, 0x5f, 0x6f, 0x66, 0x5f, 0x65,
	0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x11, 0x79, 0x65, 0x61, 0x72, 0x73, 0x4f, 0x66, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e,
	0x63, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x70, 0x65, 0x63,
	0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x6e,
	0x5f, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x6f, 0x6e, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x33, 0x0a, 0x17, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4c, 0x69, 0x66, 0x65, 0x67, 0x75, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x28,
	0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x66, 0x65, 0x67, 0x75, 0x61, 0x72,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x33, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x4c, 0x69, 0x66, 0x65, 0x67, 0x75, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0xc9, 0x02,
	0x0a, 0x10, 0x4c, 0x69, 0x66, 0x65, 0x67, 0x75, 0x61, 0x72, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x4e, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x66, 0x65,
	0x67, 0x75, 0x61, 0x72, 0x64, 0x12, 0x1c, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4c, 0x69, 0x66, 0x65, 0x67, 0x75, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4c, 0x69, 0x66, 0x65, 0x67, 0x75, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x45, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x66, 0x65, 0x67, 0x75, 0x61,
	0x72, 0x64, 0x12, 0x19, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x66,
	0x65, 0x67, 0x75, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x66, 0x65, 0x67, 0x75, 0x61, 0x72,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x0f, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4c, 0x69, 0x66, 0x65, 0x67, 0x75, 0x61, 0x72, 0x64, 0x12, 0x1c, 0x2e, 0x6d,
	0x61, 0x69, 0x6e, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x66, 0x65, 0x67, 0x75,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6d, 0x61, 0x69,
	0x6e, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x66, 0x65, 0x67, 0x75, 0x61, 0x72,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x0f, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4c, 0x69, 0x66, 0x65, 0x67, 0x75, 0x61, 0x72, 0x64, 0x12, 0x1c, 0x2e, 0x6d,
	0x61, 0x69, 0x6e, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x66, 0x65, 0x67, 0x75,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6d, 0x61, 0x69,
	0x6e, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x66, 0x65, 0x67, 0x75, 0x61, 0x72,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_lifeguard_proto_rawDescOnce sync.Once
	file_lifeguard_proto_rawDescData = file_lifeguard_proto_rawDesc
)

func file_lifeguard_proto_rawDescGZIP() []byte {
	file_lifeguard_proto_rawDescOnce.Do(func() {
		file_lifeguard_proto_rawDescData = protoimpl.X.CompressGZIP(file_lifeguard_proto_rawDescData)
	})
	return file_lifeguard_proto_rawDescData
}

var file_lifeguard_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_lifeguard_proto_goTypes = []interface{}{
	(*CreateLifeguardRequest)(nil),  // 0: main.CreateLifeguardRequest
	(*CreateLifeguardResponse)(nil), // 1: main.CreateLifeguardResponse
	(*GetLifeguardRequest)(nil),     // 2: main.GetLifeguardRequest
	(*GetLifeguardResponse)(nil),    // 3: main.GetLifeguardResponse
	(*UpdateLifeguardRequest)(nil),  // 4: main.UpdateLifeguardRequest
	(*UpdateLifeguardResponse)(nil), // 5: main.UpdateLifeguardResponse
	(*DeleteLifeguardRequest)(nil),  // 6: main.DeleteLifeguardRequest
	(*DeleteLifeguardResponse)(nil), // 7: main.DeleteLifeguardResponse
}
var file_lifeguard_proto_depIdxs = []int32{
	0, // 0: main.LifeguardService.CreateLifeguard:input_type -> main.CreateLifeguardRequest
	2, // 1: main.LifeguardService.GetLifeguard:input_type -> main.GetLifeguardRequest
	4, // 2: main.LifeguardService.UpdateLifeguard:input_type -> main.UpdateLifeguardRequest
	6, // 3: main.LifeguardService.DeleteLifeguard:input_type -> main.DeleteLifeguardRequest
	1, // 4: main.LifeguardService.CreateLifeguard:output_type -> main.CreateLifeguardResponse
	3, // 5: main.LifeguardService.GetLifeguard:output_type -> main.GetLifeguardResponse
	5, // 6: main.LifeguardService.UpdateLifeguard:output_type -> main.UpdateLifeguardResponse
	7, // 7: main.LifeguardService.DeleteLifeguard:output_type -> main.DeleteLifeguardResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lifeguard_proto_init() }
func file_lifeguard_proto_init() {
	if File_lifeguard_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lifeguard_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLifeguardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lifeguard_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLifeguardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lifeguard_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLifeguardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lifeguard_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLifeguardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lifeguard_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLifeguardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lifeguard_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLifeguardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lifeguard_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLifeguardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lifeguard_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLifeguardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lifeguard_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lifeguard_proto_goTypes,
		DependencyIndexes: file_lifeguard_proto_depIdxs,
		MessageInfos:      file_lifeguard_proto_msgTypes,
	}.Build()
	File_lifeguard_proto = out.File
	file_lifeguard_proto_rawDesc = nil
	file_lifeguard_proto_goTypes = nil
	file_lifeguard_proto_depIdxs = nil
}
